using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ScreenCapter : MonoBehaviour
{
	public int screenshotCount = 0;

	float fixedTime = 0f;

	void Update()
	{
		fixedTime += Time.deltaTime;
		// F12 콣쟍 얈있챹 웒 쫔콜쟗쨙 췶쐑
		if (fixedTime > 3f)
		{
			TakeScreenshot();
			fixedTime = 0f;
		}

	}

	public void TakeScreenshot()
	{
		// 쫔콜쟗쨙 퀛첊 첇쟎 쨥촋
		string screenshotFilename = string.Format("Screenshot_{0}.png", screenshotCount);
		// 쫔콜쟗쨙 췶쐑
		ScreenCapture.CaptureScreenshot(screenshotFilename);
		screenshotCount++;
		Debug.Log("쫔콜쟗쨙 첰천왉: " + screenshotFilename);
	}
}
